# coding: utf-8

"""
    EBI OLS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class ResourcesApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def api(self, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.api(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :return: Api
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.api_with_http_info(**kwargs)
        else:
            (data) = self.api_with_http_info(**kwargs)
            return data

    def api_with_http_info(self, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.api_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :return: Api
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Api',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def call_property(self, ontology, iri, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.call_property(ontology, iri, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param str iri:  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.call_property_with_http_info(ontology, iri, **kwargs)
        else:
            (data) = self.call_property_with_http_info(ontology, iri, **kwargs)
            return data

    def call_property_with_http_info(self, ontology, iri, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.call_property_with_http_info(ontology, iri, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param str iri:  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ontology', 'iri']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method call_property" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ontology' is set
        if ('ontology' not in params) or (params['ontology'] is None):
            raise ValueError("Missing the required parameter `ontology` when calling `call_property`")
        # verify the required parameter 'iri' is set
        if ('iri' not in params) or (params['iri'] is None):
            raise ValueError("Missing the required parameter `iri` when calling `call_property`")


        collection_formats = {}

        path_params = {}
        if 'ontology' in params:
            path_params['ontology'] = params['ontology']
        if 'iri' in params:
            path_params['iri'] = params['iri']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/ontologies/{ontology}/properties/{iri}', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def concept(self, ontology, iri, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.concept(ontology, iri, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param str iri:  (required)
        :return: Term
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.concept_with_http_info(ontology, iri, **kwargs)
        else:
            (data) = self.concept_with_http_info(ontology, iri, **kwargs)
            return data

    def concept_with_http_info(self, ontology, iri, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.concept_with_http_info(ontology, iri, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param str iri:  (required)
        :return: Term
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ontology', 'iri']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method concept" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ontology' is set
        if ('ontology' not in params) or (params['ontology'] is None):
            raise ValueError("Missing the required parameter `ontology` when calling `concept`")
        # verify the required parameter 'iri' is set
        if ('iri' not in params) or (params['iri'] is None):
            raise ValueError("Missing the required parameter `iri` when calling `concept`")


        collection_formats = {}

        path_params = {}
        if 'ontology' in params:
            path_params['ontology'] = params['ontology']
        if 'iri' in params:
            path_params['iri'] = params['iri']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/ontologies/{ontology}/terms/{iri}', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Term',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def concepts(self, ontology, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.concepts(ontology, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param int page: 
        :param int size: 
        :return: Terms
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.concepts_with_http_info(ontology, **kwargs)
        else:
            (data) = self.concepts_with_http_info(ontology, **kwargs)
            return data

    def concepts_with_http_info(self, ontology, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.concepts_with_http_info(ontology, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param int page: 
        :param int size: 
        :return: Terms
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ontology', 'page', 'size']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method concepts" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ontology' is set
        if ('ontology' not in params) or (params['ontology'] is None):
            raise ValueError("Missing the required parameter `ontology` when calling `concepts`")


        collection_formats = {}

        path_params = {}
        if 'ontology' in params:
            path_params['ontology'] = params['ontology']

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))
        if 'size' in params:
            query_params.append(('size', params['size']))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/ontologies/{ontology}/terms', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Terms',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def individual(self, ontology, iri, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.individual(ontology, iri, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param str iri:  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.individual_with_http_info(ontology, iri, **kwargs)
        else:
            (data) = self.individual_with_http_info(ontology, iri, **kwargs)
            return data

    def individual_with_http_info(self, ontology, iri, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.individual_with_http_info(ontology, iri, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param str iri:  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ontology', 'iri']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method individual" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ontology' is set
        if ('ontology' not in params) or (params['ontology'] is None):
            raise ValueError("Missing the required parameter `ontology` when calling `individual`")
        # verify the required parameter 'iri' is set
        if ('iri' not in params) or (params['iri'] is None):
            raise ValueError("Missing the required parameter `iri` when calling `individual`")


        collection_formats = {}

        path_params = {}
        if 'ontology' in params:
            path_params['ontology'] = params['ontology']
        if 'iri' in params:
            path_params['iri'] = params['iri']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/ontologies/{ontology}/individuals/{iri}', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def individuals(self, ontology, iri, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.individuals(ontology, iri, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param str iri:  (required)
        :param int page: 
        :param int size: 
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.individuals_with_http_info(ontology, iri, **kwargs)
        else:
            (data) = self.individuals_with_http_info(ontology, iri, **kwargs)
            return data

    def individuals_with_http_info(self, ontology, iri, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.individuals_with_http_info(ontology, iri, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param str iri:  (required)
        :param int page: 
        :param int size: 
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ontology', 'iri', 'page', 'size']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method individuals" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ontology' is set
        if ('ontology' not in params) or (params['ontology'] is None):
            raise ValueError("Missing the required parameter `ontology` when calling `individuals`")
        # verify the required parameter 'iri' is set
        if ('iri' not in params) or (params['iri'] is None):
            raise ValueError("Missing the required parameter `iri` when calling `individuals`")


        collection_formats = {}

        path_params = {}
        if 'ontology' in params:
            path_params['ontology'] = params['ontology']
        if 'iri' in params:
            path_params['iri'] = params['iri']

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))
        if 'size' in params:
            query_params.append(('size', params['size']))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/ontologies/{ontology}/individuals', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def ontologies(self, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.ontologies(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int page: 
        :param int size: 
        :return: Ontologies
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.ontologies_with_http_info(**kwargs)
        else:
            (data) = self.ontologies_with_http_info(**kwargs)
            return data

    def ontologies_with_http_info(self, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.ontologies_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int page: 
        :param int size: 
        :return: Ontologies
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page', 'size']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ontologies" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))
        if 'size' in params:
            query_params.append(('size', params['size']))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/ontologies', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Ontologies',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def ontology(self, ontology, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.ontology(ontology, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :return: Ontology
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.ontology_with_http_info(ontology, **kwargs)
        else:
            (data) = self.ontology_with_http_info(ontology, **kwargs)
            return data

    def ontology_with_http_info(self, ontology, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.ontology_with_http_info(ontology, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :return: Ontology
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ontology']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ontology" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ontology' is set
        if ('ontology' not in params) or (params['ontology'] is None):
            raise ValueError("Missing the required parameter `ontology` when calling `ontology`")


        collection_formats = {}

        path_params = {}
        if 'ontology' in params:
            path_params['ontology'] = params['ontology']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/ontologies/{ontology}', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Ontology',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def properties(self, ontology, iri, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.properties(ontology, iri, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param str iri:  (required)
        :param int page: 
        :param int size: 
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.properties_with_http_info(ontology, iri, **kwargs)
        else:
            (data) = self.properties_with_http_info(ontology, iri, **kwargs)
            return data

    def properties_with_http_info(self, ontology, iri, **kwargs):
        """
        
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.properties_with_http_info(ontology, iri, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str ontology:  (required)
        :param str iri:  (required)
        :param int page: 
        :param int size: 
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ontology', 'iri', 'page', 'size']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method properties" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ontology' is set
        if ('ontology' not in params) or (params['ontology'] is None):
            raise ValueError("Missing the required parameter `ontology` when calling `properties`")
        # verify the required parameter 'iri' is set
        if ('iri' not in params) or (params['iri'] is None):
            raise ValueError("Missing the required parameter `iri` when calling `properties`")


        collection_formats = {}

        path_params = {}
        if 'ontology' in params:
            path_params['ontology'] = params['ontology']
        if 'iri' in params:
            path_params['iri'] = params['iri']

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))
        if 'size' in params:
            query_params.append(('size', params['size']))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/ontologies/{ontology}/properties', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
