---
swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "PROXY OLS API"
  contact:
    email: "apiteam@swagger.io"
host: "176.31.200.199:80"
basePath: "/"
tags:
- name: "resource"
  description: ""
- name: "search"
  description: ""
schemes:
- "http"
paths:
  /repositories:
    get:
      tags:
      - "resource"
      summary: ""
      description: ""
      operationId: "repositories"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/repository"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/error"
      x-swagger-router-controller: "swagger_server.controllers.resource_controller"
  /repositories/{repository}/ontologies:
    get:
      tags:
      - "resource"
      summary: ""
      description: ""
      operationId: "ontologies"
      parameters:
      - name: "repository"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "plain"
        in: "query"
        description: ""
        required: false
        type: "boolean"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ontology"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/error"
      x-swagger-router-controller: "swagger_server.controllers.resource_controller"
  /repositories/{repository}/ontologies/{ontology}/concepts:
    get:
      tags:
      - "resource"
      summary: ""
      description: ""
      operationId: "concepts"
      parameters:
      - name: "repository"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "ontology"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "plain"
        in: "query"
        description: ""
        required: false
        type: "boolean"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/concept"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/error"
      x-swagger-router-controller: "swagger_server.controllers.resource_controller"
  /repositories/{repository}/ontologies/{ontology}/metadata:
    get:
      tags:
      - "resource"
      summary: ""
      description: ""
      operationId: "metadata"
      parameters:
      - name: "repository"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "ontology"
        in: "path"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/error"
      x-swagger-router-controller: "swagger_server.controllers.resource_controller"
definitions:
  error:
    type: "object"
    properties:
      error:
        type: "string"
      status:
        type: "integer"
        format: "int64"
  repositories:
    type: "array"
    items:
      $ref: "#/definitions/repository"
  repository:
    type: "object"
    properties:
      "@id":
        type: "string"
      "@type":
        type: "string"
        default: "http://www.w3.org/ns/dcat#Dataset"
      "dcat:landingPage":
        type: "string"
      "dct:title":
        type: "string"
  ontologies:
    type: "array"
    items:
      $ref: "#/definitions/ontology"
  ontology:
    type: "object"
    properties:
      "schema:includedInDataCatalog":
        type: "string"
      "@id":
        type: "string"
      "@type":
        type: "string"
        default: "http://www.w3.org/2002/07/owl#Ontology"
      "dct:title":
        type: "string"
      "dct:description":
        type: "string"
      "omv:acronym":
        type: "string"
      "owl:versionInfo":
        type: "string"
      "dct:modified":
        type: "string"
  concepts:
    type: "array"
    items:
      $ref: "#/definitions/concept"
  concept:
    type: "object"
    properties:
      "rdfs:isDefinedBy":
        type: "string"
      "@id":
        type: "string"
      "skos:prefLabel":
        type: "string"
      "skos:definition":
        type: "string"
      "skos:note":
        type: "string"
      "skos:altLabel":
        type: "string"
