# coding: utf-8

"""
    PROXY OLS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.ontologies import Ontologies


class TestOntologies(unittest.TestCase):
    """ Ontologies unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOntologies(self):
        """
        Test Ontologies
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.ontologies.Ontologies()
        pass


if __name__ == '__main__':
    unittest.main()
