# coding: utf-8

"""
    PROXY OLS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.resource_api import ResourceApi


class TestResourceApi(unittest.TestCase):
    """ ResourceApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.resource_api.ResourceApi()

    def tearDown(self):
        pass

    def test_concepts(self):
        """
        Test case for concepts

        
        """
        pass

    def test_ontologies(self):
        """
        Test case for ontologies

        
        """
        pass

    def test_repositories(self):
        """
        Test case for repositories

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
