# coding: utf-8

"""
    PROXY OLS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Repository(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'name': 'str',
        'description': 'str',
        'version': 'str'
    }

    attribute_map = {
        'url': 'url',
        'name': 'name',
        'description': 'description',
        'version': 'version'
    }

    def __init__(self, url=None, name=None, description=None, version=None):
        """
        Repository - a model defined in Swagger
        """

        self._url = None
        self._name = None
        self._description = None
        self._version = None

        if url is not None:
          self.url = url
        if name is not None:
          self.name = name
        if description is not None:
          self.description = description
        if version is not None:
          self.version = version

    @property
    def url(self):
        """
        Gets the url of this Repository.

        :return: The url of this Repository.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this Repository.

        :param url: The url of this Repository.
        :type: str
        """

        self._url = url

    @property
    def name(self):
        """
        Gets the name of this Repository.

        :return: The name of this Repository.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Repository.

        :param name: The name of this Repository.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this Repository.

        :return: The description of this Repository.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Repository.

        :param description: The description of this Repository.
        :type: str
        """

        self._description = description

    @property
    def version(self):
        """
        Gets the version of this Repository.

        :return: The version of this Repository.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this Repository.

        :param version: The version of this Repository.
        :type: str
        """

        self._version = version

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Repository):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
