# coding: utf-8

"""
    PROXY OLS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Repository(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'type': 'str',
        'dcatlanding_page': 'str',
        'dcttitle': 'str'
    }

    attribute_map = {
        'id': '@id',
        'type': '@type',
        'dcatlanding_page': 'dcat:landingPage',
        'dcttitle': 'dct:title'
    }

    def __init__(self, id=None, type='http://www.w3.org/ns/dcat#Dataset', dcatlanding_page=None, dcttitle=None):
        """
        Repository - a model defined in Swagger
        """

        self._id = None
        self._type = None
        self._dcatlanding_page = None
        self._dcttitle = None

        if id is not None:
          self.id = id
        if type is not None:
          self.type = type
        if dcatlanding_page is not None:
          self.dcatlanding_page = dcatlanding_page
        if dcttitle is not None:
          self.dcttitle = dcttitle

    @property
    def id(self):
        """
        Gets the id of this Repository.

        :return: The id of this Repository.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Repository.

        :param id: The id of this Repository.
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """
        Gets the type of this Repository.

        :return: The type of this Repository.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Repository.

        :param type: The type of this Repository.
        :type: str
        """

        self._type = type

    @property
    def dcatlanding_page(self):
        """
        Gets the dcatlanding_page of this Repository.

        :return: The dcatlanding_page of this Repository.
        :rtype: str
        """
        return self._dcatlanding_page

    @dcatlanding_page.setter
    def dcatlanding_page(self, dcatlanding_page):
        """
        Sets the dcatlanding_page of this Repository.

        :param dcatlanding_page: The dcatlanding_page of this Repository.
        :type: str
        """

        self._dcatlanding_page = dcatlanding_page

    @property
    def dcttitle(self):
        """
        Gets the dcttitle of this Repository.

        :return: The dcttitle of this Repository.
        :rtype: str
        """
        return self._dcttitle

    @dcttitle.setter
    def dcttitle(self, dcttitle):
        """
        Sets the dcttitle of this Repository.

        :param dcttitle: The dcttitle of this Repository.
        :type: str
        """

        self._dcttitle = dcttitle

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Repository):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
