# coding: utf-8

"""
    EBI OLS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class OntologiesEmbedded(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ontologies': 'list[Ontology]'
    }

    attribute_map = {
        'ontologies': 'ontologies'
    }

    def __init__(self, ontologies=None):
        """
        OntologiesEmbedded - a model defined in Swagger
        """

        self._ontologies = None

        if ontologies is not None:
          self.ontologies = ontologies

    @property
    def ontologies(self):
        """
        Gets the ontologies of this OntologiesEmbedded.

        :return: The ontologies of this OntologiesEmbedded.
        :rtype: list[Ontology]
        """
        return self._ontologies

    @ontologies.setter
    def ontologies(self, ontologies):
        """
        Sets the ontologies of this OntologiesEmbedded.

        :param ontologies: The ontologies of this OntologiesEmbedded.
        :type: list[Ontology]
        """

        self._ontologies = ontologies

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, OntologiesEmbedded):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
