# coding: utf-8

"""
    EBI OLS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SuggestResponseDocs(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'autosuggest': 'str'
    }

    attribute_map = {
        'autosuggest': 'autosuggest'
    }

    def __init__(self, autosuggest=None):
        """
        SuggestResponseDocs - a model defined in Swagger
        """

        self._autosuggest = None

        if autosuggest is not None:
          self.autosuggest = autosuggest

    @property
    def autosuggest(self):
        """
        Gets the autosuggest of this SuggestResponseDocs.

        :return: The autosuggest of this SuggestResponseDocs.
        :rtype: str
        """
        return self._autosuggest

    @autosuggest.setter
    def autosuggest(self, autosuggest):
        """
        Sets the autosuggest of this SuggestResponseDocs.

        :param autosuggest: The autosuggest of this SuggestResponseDocs.
        :type: str
        """

        self._autosuggest = autosuggest

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SuggestResponseDocs):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
